考核1
试题见名为"考核1"的压缩包，试题介绍：下列图片为某物质在高温下溶解的过程，请使用OpenCV将图片中的物质轮廓描绘到原图片，并计算轮廓的中心坐标，周长和面积，将计算好的量与自己的名字打图片上，具体做法参见“示例”
做两张彩色图，一张灰度图

In [6]:
#彩色1
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont# 引入 ImageDraw 
img0=cv2.imread(r"C:\Users\Lenovo\Downloads\feishu\1.bmp")
img = cv2.GaussianBlur(img0, (3,3),0)#高斯模糊
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))
imgp = cv2.dilate(img,kernel) #膨胀
imggray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)#灰度
ret,thresh=cv2.threshold(imggray,176,255,0)#二值化，指定的阈值，大于阈值的像素被分配为maxval，小于阈值的像素被分配为0
contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#findcontour()函数中有三个参数，第一个是原图像，第二个是轮廓检索模式，第三个是轮廓逼近方法，输出等高线和层次结构。
for i in range(len(contours)):
	area = cv2.contourArea(contours[i])#计算面积
	if area>14500 and area<20000:
		a=i#用面积筛选轮廓
cnt=contours[a]
epsilon = 0.001 * cv2.arcLength(cnt, True)
# 获取近似轮廓，
approx = cv2.approxPolyDP(cnt, epsilon,True)
cv2.drawContours(img,[approx],-1,(255,0,0),3)
m=cv2.moments(cnt)
cx=int(m['m10']/m['m00'])
cy=int(m['m01']/m['m00'])#计算中心
area=cv2.contourArea(cnt)#计算面积
perimeter=cv2.arcLength(cnt,True)#计算周长
if (isinstance(img, np.ndarray)):  # 判断是否 OpenCV 图片类型
    imgPIL = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))#实现array到image的转换
pos = (50, 20)  # (left, top)，字符串左上角坐标
color = (255, 255, 255)  # 字体颜色
textSize = 40#字体大小
drawPIL = ImageDraw.Draw(imgPIL)# 创建 Draw 对象
fontText = ImageFont.truetype("font/simsun.ttc", textSize, encoding="utf-8")
#创建一个字体对象，encoding-使用哪种字体编码
drawPIL.text(pos, f'吴兆芸\n轮廓面积:{area}\n周长:{perimeter}\n中心:({cx},{cy})', color, font=fontText)
# 第一个参数：指定文字区域的左上角在图片上的位置(x,y)
# 第二个参数：文字内容
# 第三个参数：颜色
# 第四个参数：字体
imgPutText = cv2.cvtColor(np.asarray(imgPIL), cv2.COLOR_RGB2BGR)
#实现image到array的转换
cv2.imshow("imgPutText", imgPutText)  # 显示叠加图像 imgAdd
key = cv2.waitKey(0)  # 等待按键命令


In [ ]:
#彩色2
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont
img0=cv2.imread(r"C:\Users\Lenovo\Downloads\feishu\4.bmp")
img = cv2.GaussianBlur(img0, (3,3),0)#高斯模糊
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))
imgp = cv2.dilate(img,kernel) #膨胀
imggray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)#灰度
ret,thresh=cv2.threshold(imggray,163,255,0)#二值化，指定的阈值，大于阈值的像素被分配为maxval，小于阈值的像素被分配为0
contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#findcontour()函数中有三个参数，第一个是原图像，第二个是轮廓检索模式，第三个是轮廓逼近方法，输出等高线和层次结构。

for i in range(len(contours)):
	area = cv2.contourArea(contours[i])#计算面积
	if area>3000 and area<3300:
		a=i#用面积筛选轮廓
cnt=contours[a]
epsilon = 0.001 * cv2.arcLength(cnt, True)
# 获取近似轮廓，
approx = cv2.approxPolyDP(cnt, epsilon,True)
cv2.drawContours(img,[approx],-1,(255,0,0),3)
m=cv2.moments(cnt)
cx=int(m['m10']/m['m00'])
cy=int(m['m01']/m['m00'])#计算中心
area=cv2.contourArea(cnt)#计算面积
perimeter=cv2.arcLength(cnt,True)#计算周长
if (isinstance(img, np.ndarray)):  # 判断是否 OpenCV 图片类型
    imgPIL = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
pos = (50, 20)  # (left, top)，字符串左上角坐标
color = (255, 255, 255)  # 字体颜色
textSize = 40#字体大小
drawPIL = ImageDraw.Draw(imgPIL)
fontText = ImageFont.truetype("font/simsun.ttc", textSize, encoding="utf-8")
drawPIL.text(pos, f'吴兆芸\n轮廓面积:{area}\n周长:{perimeter}\n中心:({cx},{cy})', color, font=fontText)
imgPutText = cv2.cvtColor(np.asarray(imgPIL), cv2.COLOR_RGB2BGR)
cv2.namedWindow("result", 0)
cv2.resizeWindow("result", 400, 300)
cv2.imshow("result", imgPutText)  # 显示叠加图像 imgAdd
key = cv2.waitKey(0)  # 等待按键命令

In [7]:
#灰色1
import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont
img0=cv2.imread(r"C:\Users\Lenovo\Downloads\feishu\6.bmp")
img = cv2.GaussianBlur(img0, (3,3),0)#高斯模糊
kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(3, 3))
imgp = cv2.dilate(img,kernel) #膨胀
imggray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)#灰度
ret,thresh=cv2.threshold(imggray,206,255,0)#二值化，指定的阈值，大于阈值的像素被分配为maxval，小于阈值的像素被分配为0
contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#findcontour()函数中有三个参数，第一个是原图像，第二个是轮廓检索模式，第三个是轮廓逼近方法，输出等高线和层次结构。
for i in range(len(contours)):
	area = cv2.contourArea(contours[i])#计算面积
	if area>8000 and area<9000:
		a=i#用面积筛选轮廓
cnt=contours[a]
epsilon = 0.001 * cv2.arcLength(cnt, True)
# 获取近似轮廓，
approx = cv2.approxPolyDP(cnt, epsilon,True)
cv2.drawContours(img,[approx],-1,(255,0,0),3)
m=cv2.moments(cnt)
cx=int(m['m10']/m['m00'])
cy=int(m['m01']/m['m00'])#计算中心
area=cv2.contourArea(cnt)#计算面积
perimeter=cv2.arcLength(cnt,True)#计算周长
if (isinstance(img, np.ndarray)):  # 判断是否 OpenCV 图片类型
    imgPIL = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
pos = (50, 20)  # (left, top)，字符串左上角坐标
color = (255, 255, 255)  # 字体颜色
textSize = 40#字体大小
drawPIL = ImageDraw.Draw(imgPIL)
fontText = ImageFont.truetype("font/simsun.ttc", textSize, encoding="utf-8")
drawPIL.text(pos, f'吴兆芸\n轮廓面积:{area}\n周长:{perimeter}\n中心:({cx},{cy})', color, font=fontText)
imgPutText = cv2.cvtColor(np.asarray(imgPIL), cv2.COLOR_RGB2BGR)
cv2.namedWindow("result", 0)
cv2.resizeWindow("result", 400, 300)
cv2.imshow("result", imgPutText)  # 显示叠加图像 imgAdd
key = cv2.waitKey(0)  # 等待按键命令

考核2
识别手势剪刀，石头，布

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

#高斯滤波
def GausBlur(img):
    gaus = cv2.GaussianBlur(img,(5,5),2)   #(5, 5)表示高斯矩阵的长与宽都是5，标准差取2
    return gaus
#肤色检查处理
def skin_img(gaus_img):
    ycrcb= cv2.cvtColor(gaus_img, cv2.COLOR_BGR2YCrCb) # 把图像转换到YUV色域
    (y, cr, cb) = cv2.split(ycrcb) # 图像分割, 分别获取y, cr, br通道图像
    cr1 = cv2.GaussianBlur(cr,(3,3),0) # 对cr通道分量进行高斯滤波#高斯滤波, cr 是待滤波的源图像数据, (5,5)是值窗口大小, 0 是指根据窗口大小来计算高斯函数标准差
	# 根据OTSU算法求图像阈值, 对图像进行二值化_, 
    ret,skin = cv2.threshold(cr1, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return skin
#开运算操作
capture=cv2.VideoCapture(0) #捕获摄像头图像  0位默认的摄像头 笔记本的自带摄像头  1为外界摄像头
while(capture.isOpened()):
    ret,img = capture.read()  #视频捕获帧
    img = cv2.resize(img,(640,480)) #设置窗口大小
    #高斯滤波
    gaus_img = GausBlur(img)
    #肤色检测处理
    skin= skin_img(gaus_img)
    #轮廓检测
    contours, hierarchy = cv2.findContours(skin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)  
    #描绘轮廓
    for i in range(len(contours)):
        area = cv2.contourArea(contours[i])#计算面积
        if area>500 :
            a=i#用面积筛选轮廓
    cnt=contours[a]   
    epsilon = 0.001 * cv2.arcLength(cnt, True)
    # 获取近似轮廓，
    approx = cv2.approxPolyDP(cnt, epsilon,True)
    cv2.drawContours(img,[approx],-1,(255,0,0),3)
    area=cv2.contourArea(cnt)
    hull = cv2.convexHull( cnt )
    cv2.drawContours(img,[hull],-1,(255,0,0),3)
    areahull=cv2.contourArea(hull)
    a=areahull/area
    if a<1.2:
	    m=0
    elif a<1.5:
        m=1
    else:
	    m=2
    text = ["rock", "scissors", "paper"]
    cv2.putText(img, text[m], (30,30), cv2.FONT_HERSHEY_SIMPLEX, 1,(0,0,255),2)
    cv2.imshow("Video",img)     #显示窗口 查看实时图像
    if cv2.waitKey(1) & 0xFF == ord('q'):   #按Q关闭所有窗口  
        break
#执行完后释放窗口
capture.release()
cv2.waitKey(0)
cv2.destroyAllWindows()

考核3

1、描绘出视频中白线的中轴线（除白色外颜色自选）；

2、视频中显示白线与图片竖直方向上的夹角；

3、视频中显示白线中轴线与图片中心点的横向距离（取轴线上与中心点Y方向相同的点）。

4、视频中出现转弯或十字交叉线时，不做2和3的操作，而是输出转弯角度或是否有十字。


In [1]:
 import cv2  
import numpy as np
import math
from cv2 import ximgproc
from PIL import Image, ImageDraw, ImageFont# 引入 ImageDraw 
def zi(text,img):
    if (isinstance(img, np.ndarray)):  # 判断是否 OpenCV 图片类型
        imgPIL = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))#实现array到image的转换
    pos = (50, 20)  # (left, top)，字符串左上角坐标
    color = (255, 255, 255)  # 字体颜色
    textSize = 20#字体大小
    drawPIL = ImageDraw.Draw(imgPIL)# 创建 Draw 对象
    fontText = ImageFont.truetype("font/simsun.ttc", textSize, encoding="utf-8")
    #创建一个字体对象，encoding-使用哪种字体编码   
    drawPIL.text(pos, text, color, font=fontText)
    # 第一个参数：指定文字区域的左上角在图片上的位置(x,y)
    # 第二个参数：文字内容
    # 第三个参数：颜色
    # 第四个参数：字体
    imgPutText = cv2.cvtColor(np.asarray(imgPIL), cv2.COLOR_RGB2BGR)
    #实现image到array的转换
    cv2.imshow("imgPutText", imgPutText)  # 显示叠加图像 imgAdd
def zhongzhou(img0):
    img = cv2.GaussianBlur(img0, (3,3),0)#高斯模糊
    # 转换为HSV颜色空间
    hsv_image = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    # 设置白色的阈值范围
    lower_white = (30, 0, 50)
    upper_white = (80, 40, 255)
    # 提取白色部分
    white_mask = cv2.inRange(hsv_image, lower_white, upper_white)
    ret,thresh=cv2.threshold(white_mask,110,255,0)#二值化，指定的阈值，大于阈值的像素被分配为maxval，小于阈值的像素被分配为0
    contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    #findcontour()函数中有三个参数，第一个是原图像，第二个是轮廓检索模式，第三个是轮廓逼近方法，输出等高线和层次结构。
    for i in range(len(contours)):
        area = cv2.contourArea(contours[i])#计算面积
        if area>10000:
            a=i#用面积筛选轮廓
    cnt=contours[a]
    area = cv2.contourArea(contours[a])#计算面积
    epsilon = 0.001 * cv2.arcLength(cnt, True)
    # 获取近似轮廓，
    approx = cv2.approxPolyDP(cnt, epsilon,True)
    cv2.drawContours(img0,[approx],-1,(255,0,0),3)
    # 骨架化
    skel = cv2.ximgproc.thinning(thresh)
    # 连接骨架
    contours, hierarchy = cv2.findContours(skel, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)#在骨架图像上找到轮廓。
    #cv2.RETR_EXTERNAL表示只检索最外层的轮廓
    #cv2.CHAIN_APPROX_SIMPLE表示压缩轮廓，即只存储端点。
    rows,cols = skel.shape[:2]#获取骨架图像的高度和宽度。
    [vx,vy,x,y] = cv2.fitLine(cnt, cv2.DIST_L2,0,0.01,0.01)#使用L2距离对轮廓cnt进行直线拟合。
    #返回的vx和vy是直线的斜率和截距，x和y是直线上的一点。
    lefty = int((-x*vy/vx) + y)#直线在图像左边的交点y坐标。
    righty = int(((cols-x)*vy/vx)+y)
    cv2.line(img0,(cols-1,righty),(0,lefty),(0,255,0),2)
    slope = -vy / vx if vx != 0 else float('inf')
    jiao0 = math.atan(slope) #角度=actan（斜率）（以弧度为单位）
    jiao1= np.degrees(jiao0)#转化为角度
    if jiao1<0:
        jiao=-90-jiao1
    elif jiao1>0:
        jiao=90-jiao1
    # 找到图像中心点y坐标  
    center_y = rows // 2  
    distance = (lefty + righty) / 2 - center_y   
    hull= cv2.convexHull(cnt)  
    # 遍历每个轮廓和其凸包   
    # 计算凸包上的顶点数  
    num_hull_points = len(hull) // 2  # 每个点有两个坐标值  
    num_cnt_points = len(cnt) // 2  # 每个点有两个坐标值  
        # 判断是否为转弯或十字交叉  
    if jiao <45 and num_hull_points < num_cnt_points:
        text= f'角度={jiao}\n距离={distance}'
    elif jiao>45 and num_hull_points < num_cnt_points:  # 可能是转弯  
            # 计算转弯角度
            rect = cv2.minAreaRect(cnt) 
            angle = rect[2]  # 旋转角度，范围是-90到90度，顺时针为正。  
            angle = angle * 180 / np.pi  # 将弧度转换为度数  
            text= f'转弯角度={angle}'  
    elif num_hull_points == 4 and len(cnt) > 4:  # 可能是十字交叉  
            text= f'十字交叉'   
    zi(text,img0)
# 打开视频文件  
capture = cv2.VideoCapture(r"C:\Users\Lenovo\Downloads\feishu\RC.mp4")  
while (capture.isOpened()): # 笔记本内置摄像头被打开后
    retval, image = capture.read()
    zhongzhou(image)
    #cv2.imshow("Video", image) # 在窗口中显示读取到的视频
    key = cv2.waitKey(10) # 窗口的图像刷新时间为1毫秒
    if key == 32: # 如果按下空格键
        break
capture.release() # 关闭笔记本内置摄像头
cv2.destroyAllWindows() # 销毁显示摄像头视频的窗口

考核4
进行相机标定，使用标定好的相机用solvepnp算法测距

In [3]:
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import cv2
import numpy as np
import glob

# 设置寻找亚像素角点的参数，采用的停止准则是最大循环次数30和最大误差容限0.001
criteria = (cv2.TERM_CRITERIA_MAX_ITER | cv2.TERM_CRITERIA_EPS, 30, 0.001)

# 获取标定板角点的位置
objp = np.zeros((6 * 9, 3), np.float32)  #格子数为7行10列，内角点为6*9的棋盘格图片
objp[:, :2] = np.mgrid[0:9, 0:6].T.reshape(-1, 2)  # 将世界坐标系建在标定板上，所有点的Z坐标全部为0，所以只需要赋值x和y

obj_points = []  # 存储3D点
img_points = []  # 存储2D点

images = glob.glob("C:/Users/Lenovo/Downloads/feishu/1/*.jpg",)
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    size = gray.shape[::-1]
    ret, corners = cv2.findChessboardCorners(gray, (6, 9), None)  #提取角点:第一个参数为图片，第二个为图片横纵角点的个数。

    if ret:
        obj_points.append(objp)

        corners2 = cv2.cornerSubPix(gray, corners, (5, 5), (-1, -1), criteria)  # 在原角点的基础上寻找亚像素角点
        # 找寻亚像素角点：cornerSubPix(gray, corners, (winsize, winsize), (-1, -1), criteria)
        # winsize为搜索窗口边长的一半。
        # zeroZone：搜索区域中间的dead region边长的一半，有时用于避免自相关矩阵的奇异性。如果值设为(-1,-1)则表示没有这个区域。
        # criteria：角点精准化迭代过程的终止条件。也就是当迭代次数超过criteria.maxCount，或者角点位置变化小于criteria.epsilon时，停止迭代过程。

        if [corners2]:
            img_points.append(corners2)
        else:
            img_points.append(corners)

        cv2.drawChessboardCorners(img, (6, 9), corners, ret)  # 记住，OpenCV的绘制函数一般无返回值
        # 可以使用该函数把角点画出来：drawChessboardCorners(image, (w, h), corners, ret);其中corners和ret为第一个函数的输出值。
        #cv2.imshow('img', img)
        #cv2.waitKey(0) # 直到你按下任意一个键，才被关掉
        # 在delaytime时间内,按键盘,返回所按键的ASCII值; 若未在delaytime时间内按任何键,返回-1; 其中,dalaytime: 单位ms

print (len(img_points))
cv2.destroyAllWindows()

# 标定
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(obj_points, img_points, size, None, None)

print ("ret:", ret)
print ("mtx:\n", mtx)  # 内参数矩阵
print ("dist:\n", dist)  # 畸变系数   distortion cofficients = (k_1,k_2,p_1,p_2,k_3)
print ("rvecs:\n", rvecs)  # 旋转向量  # 外参数
print ("tvecs:\n", tvecs)  # 平移向量  # 外参数

print("-----------------------------------------------------")

# 畸变校正
img = cv2.imread(images[9])
h, w = img.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))  #显示更大范围的图片（正常重映射之后会删掉一部分图像）
print (newcameramtx)

print("------------------使用undistort函数-------------------")
dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
x, y, w, h = roi
dst1 = dst[y:y + h, x:x + w]
cv2.imwrite('calibresult21.jpg', dst1)
print ("方法一:dst的大小为:", dst1.shape)

# undistort方法二
print("-------------------使用重映射的方式-----------------------")
mapx, mapy = cv2.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w, h), 5)  # 获取映射方程
dst = cv2.remap(img, mapx, mapy, cv2.INTER_LINEAR)      # 重映射
# dst = cv2.remap(img, mapx, mapy, cv2.INTER_CUBIC)  # 重映射后，图像变小了
x, y, w, h = roi
dst2 = dst[y:y + h, x:x + w]
cv2.imwrite('calibresult22.jpg', dst2)
print ("方法二:dst的大小为:", dst2.shape ) # 图像比方法一的小

print("-------------------计算反向投影误差-----------------------")
tot_error = 0
for i in range(len(obj_points)):
    img_points2, _ = cv2.projectPoints(obj_points[i], rvecs[i], tvecs[i], mtx, dist)
    error = cv2.norm(img_points[i], img_points2, cv2.NORM_L2) / len(img_points2)
    tot_error += error

mean_error = tot_error / len(obj_points)
print ("total error: ", tot_error)
print ("mean error: ", mean_error)


12
ret: 340.05083998343775
mtx:
 [[5.94388543e+04 0.00000000e+00 1.74880950e+03]
 [0.00000000e+00 1.38799840e+05 5.76452148e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist:
 [[ 2.34007892e+02 -1.12537692e+05 -8.18535756e-02 -2.56867020e+00
   3.50444520e+04]]
rvecs:
 (array([[-1.26911422],
       [-1.09441485],
       [-1.17622785]]), array([[ 1.25651768],
       [ 1.10174568],
       [-1.19225314]]), array([[-1.24556425],
       [-1.11347533],
       [-1.1429754 ]]), array([[ 1.25177534],
       [ 1.10658221],
       [-1.18621422]]), array([[-1.26912829],
       [-1.10005714],
       [-1.17407581]]), array([[-1.2678462 ],
       [-1.09743898],
       [-1.16482562]]), array([[-1.26169342],
       [-1.09927412],
       [-1.15978292]]), array([[-1.26156826],
       [-1.10197122],
       [-1.1642144 ]]), array([[-1.25881072],
       [-1.10156814],
       [-1.15972946]]), array([[-1.27073473],
       [-1.08963274],
       [-1.157244  ]]), array([[-1.26820689],
       [-1.0933271

In [6]:
# -*- coding: utf-8 -*-

import numpy as np

# 内参数矩阵
Camera_intrinsic = {

    "mtx": np.array([[5.94388543e+04, 0.00000000e+00, 1.74880950e+03],[0.00000000e+00, 1.38799840e+05, 5.76452148e+02],[0.00000000e+00, 0.00000000e+00, 1.00000000e+00]],
               dtype=np.double),
    "dist": np.array([[2.34007892e+02,-1.12537692e+05,-8.18535756e-02,-2.56867020e+00,
   3.50444520e+04]], dtype=np.double),

}
Object = {"height": 105, "width": 150}

# 初始的HSV GUI滑块值在程序启动时加载
icol = {
    # lowHue,highHue,lowSat,highSat,lowVal,highVal
    "icol_black": (0, 180, 0, 255, 0, 46),  # 找黑色 适合白天
    "icol_gray": (0, 180, 0, 43, 46, 220),
    "icol_white": (0, 180, 0, 30, 221, 255),  # 找白色 适合晚上没灯
    "icol_red": (156, 180, 43, 255, 46, 255),

}


In [9]:
from __future__ import division
import numpy as np
import math
import cv2 
from config import *


def nothing(*arg):
    pass


half_Weight = int(Object["width"] / 2)
half_Height = int(Object["height"] / 2)


# 滑动条用以调节HSV的参数
cv2.namedWindow('colorTest')  # 为滑动条创建窗口
Icol = icol["icol_black"] # 初始化滑动条内的起始数据
cv2.createTrackbar('lowHue', 'colorTest', Icol[0], 255, nothing)
cv2.createTrackbar('highHue', 'colorTest', Icol[1], 255, nothing)

cv2.createTrackbar('lowSat', 'colorTest', Icol[2], 255, nothing)
cv2.createTrackbar('highSat', 'colorTest', Icol[3], 255, nothing)

cv2.createTrackbar('lowVal', 'colorTest', Icol[4], 255, nothing)
cv2.createTrackbar('highVal', 'colorTest', Icol[5], 255, nothing)

camera = cv2.VideoCapture(0)

while True:
    (grabbed, frame) = camera.read()
    # Get HSV values from the GUI sliders.
    lowHue = cv2.getTrackbarPos('lowHue', 'colorTest')
    lowSat = cv2.getTrackbarPos('lowSat', 'colorTest')
    lowVal = cv2.getTrackbarPos('lowVal', 'colorTest')
    highHue = cv2.getTrackbarPos('highHue', 'colorTest')
    highSat = cv2.getTrackbarPos('highSat', 'colorTest')
    highVal = cv2.getTrackbarPos('highVal', 'colorTest')

    frameBGR = cv2.GaussianBlur(frame.copy(), (7, 7), 0)  # 高斯模糊
    hsv = cv2.cvtColor(frameBGR, cv2.COLOR_BGR2HSV)  # 颜色转换
    colorLow = np.array([lowHue, lowSat, lowVal]) # 获取low HSV 的值
    colorHigh = np.array([highHue, highSat, highVal]) # 获取high HSV 的值
    mask = cv2.inRange(hsv, colorLow, colorHigh)
    edged = cv2.Canny(mask, 35, 100) # canny算子找轮廓
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (7, 7))
    dst = cv2.dilate(edged.copy(), kernel)  # 扩张，使轮廓闭合。
    (cnts, _) = cv2.findContours(dst.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)  # 找轮廓
    area = []

    # 求最大面积
    try:
        for k in range(len(cnts)):
            area.append(cv2.contourArea(cnts[k]))
        max_idx = np.argmax(np.array(area))
        cv2.drawContours(mask, cnts, max_idx, (255, 255, 255), cv2.FILLED)
        (cnts, _) = cv2.findContours(mask.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
        c = max(cnts, key=cv2.contourArea)

        marker = cv2.minAreaRect(c)
        box = np.int0(cv2.boxPoints(marker))

        cv2.drawContours(frame, [box], -1, (255, 255, 255), 2)


        obj = np.array([[-half_Weight, -half_Height, 0], [half_Weight, -half_Height, 0], [half_Weight, half_Height, 0],
                        [-half_Weight, half_Height, 0]], dtype=np.float64)  # 世界坐标
        pnts = np.array(box, dtype=np.float64) # 像素坐标

        # rotation_vector 旋转向量 translation_vector 平移向量
        (success, rvec, tvec) = cv.solvePnP(obj, pnts, Camera_intrinsic["mtx"], Camera_intrinsic["dist"])

        distance=math.sqrt(tvec[0]**2+tvec[1]**2+tvec[2]**2)/10  # 测算距离

        rvec_matrix = cv2.Rodrigues(rvec)[0]
        proj_matrix = np.hstack((rvec_matrix, rvec))
        eulerAngles = -cv2.decomposeProjectionMatrix(proj_matrix)[6]  # 欧拉角
        pitch, yaw, roll = eulerAngles[0], eulerAngles[1], eulerAngles[2]
        rot_params = np.array([yaw, pitch, roll])  # 欧拉角 数组
        # 这里pitch要变为其相反数(不知道为啥)
        cv2.putText(frame, "%.2fcm,%.2f,%.2f,%.2f" % (distance, yaw, -pitch, roll),
                    (frame.shape[1] - 500, frame.shape[0] - 20), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 255, 0), 3)

    except Exception:
        pass
    cv2.imshow('frame', frame)
    cv2.imshow('mask-plain', mask)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()



C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8384\1839703692.py:61: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  box = np.int0(cv2.boxPoints(marker))
